// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs1jkVarxySBBrZFXFJ6jQ0hoq1vWU1GI',
    appId: '1:603680480346:web:ca32707630cd9e84d00c63',
    messagingSenderId: '603680480346',
    projectId: 'wave-staging-d1b41',
    authDomain: 'wave-staging-d1b41.firebaseapp.com',
    storageBucket: 'wave-staging-d1b41.firebasestorage.app',
    measurementId: 'G-42NHVGX9J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFJuSoQeq65F_ff_sYVt1qXslUCZJpx2U',
    appId: '1:603680480346:android:45687f4af692866dd00c63',
    messagingSenderId: '603680480346',
    projectId: 'wave-staging-d1b41',
    storageBucket: 'wave-staging-d1b41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bfU-kScEgxKzns6GDYj7bkBtP5UA5zw',
    appId: '1:603680480346:ios:958e27b484ad6775d00c63',
    messagingSenderId: '603680480346',
    projectId: 'wave-staging-d1b41',
    storageBucket: 'wave-staging-d1b41.firebasestorage.app',
    iosBundleId: 'com.example.wave',
  );
}
