// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqfg-yMOvY5Wi6Fhv90KoS9HOQ1phKA4',
    appId: '1:751618338182:web:82fc1820aa1ae872fb1007',
    messagingSenderId: '751618338182',
    projectId: 'wave-prod-a529f',
    authDomain: 'wave-prod-a529f.firebaseapp.com',
    storageBucket: 'wave-prod-a529f.firebasestorage.app',
    measurementId: 'G-J14X27MMNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuhTvkInGWqoKPto0M6pV8o3dMw4HWE8',
    appId: '1:751618338182:android:1ad2bfaf0ccc4b39fb1007',
    messagingSenderId: '751618338182',
    projectId: 'wave-prod-a529f',
    storageBucket: 'wave-prod-a529f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEhBS0PTvP_vpWilq-wFA8sAXnSlpsYvM',
    appId: '1:751618338182:ios:e4385f3d6d52a67afb1007',
    messagingSenderId: '751618338182',
    projectId: 'wave-prod-a529f',
    storageBucket: 'wave-prod-a529f.firebasestorage.app',
    iosClientId: '751618338182-dhoeklr0t9b6ieqchmqld1ja19a0s7kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.wave',
  );
}
