import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:wave/app/di/injector.dart';
import 'package:wave/app/router/app_router.dart';
// ئەمە زیاد کرا بۆ گوێگرتن لە نامەکانی سەبەتە (Snackbar)
import 'package:wave/app/widgets/cart_message_listener.dart';
import 'package:wave/core/l10n/wave_localizations.dart';
import 'package:wave/core/services/force_update_service.dart';
import 'package:wave/core/settings/locale_controller.dart';
import 'package:wave/core/theme/app_theme.dart';
import 'package:wave/design_system/components/wave_skeleton.dart';
import 'package:wave/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:wave/features/cart/presentation/bloc/cart_bloc.dart';
import 'package:wave/features/notifications/data/push_handler.dart';
import 'package:wave/features/onboarding/data/onboarding_service.dart';
// Generated by `flutter gen-l10n` (run automatically by `flutter pub get`).
// Gitignored — see l10n.yaml. If your IDE flags this import on a fresh clone,
// run `flutter gen-l10n` once.
import 'package:wave/l10n/generated/app_localizations.dart';

class WaveApp extends StatefulWidget {
  const WaveApp({super.key});

  @override
  State<WaveApp> createState() => _WaveAppState();
}

class _WaveAppState extends State<WaveApp> {
  late final AuthBloc _authBloc = getIt<AuthBloc>()..add(const AuthStarted());
  bool _forceUpdate = false;
  late final AppRouter _appRouter;
  late final _AuthRefreshNotifier _authRefresh;

  @override
  void initState() {
    super.initState();

    // Held in a field so dispose can cancel its stream subscription. It was
    // constructed inline, which left the subscription alive for the process
    // lifetime with no way to reach it.
    _authRefresh = _AuthRefreshNotifier(_authBloc.stream);

    _appRouter = AppRouter(
      // Guests count as signed in for routing purposes — they have a session
      // and can browse. The narrower question of whether they can ORDER is
      // asked at the checkout gate, not here, so guest mode never bounces
      // someone out of discovery (§1).
      isSignedIn: () => _authBloc.state.status != AuthStatus.signedOut,
      needsForceUpdate: () => _forceUpdate,
      hasSeenOnboarding: () => getIt<OnboardingService>().hasSeenOnboarding,
      // Re-evaluates redirects whenever auth changes, so signing in from a
      // deep-linked checkout lands back on checkout rather than the feed.
      refreshListenable: _authRefresh,
    );

    unawaited(_checkForceUpdate());

    // Rehydrated here rather than in the BLoC constructor: it re-reads every
    // product, and doing that during DI would delay the first frame for
    // something nobody is looking at yet.
    getIt<CartBloc>().add(const CartRestored());

    // Started after the router exists, because a tap on a push that launched
    // the app from terminated state arrives almost immediately and needs
    // somewhere to navigate to.
    getIt<PushHandler>().start(
      navigate: (route) => _appRouter.router.push(route),
    );
  }

  @override
  void dispose() {
    getIt<PushHandler>().dispose();
    _authRefresh.dispose();
    super.dispose();
  }

  Future<void> _checkForceUpdate() async {
    final required = await getIt<ForceUpdateService>().isUpdateRequired();
    if (!mounted || !required) return;
    setState(() => _forceUpdate = true);
    _appRouter.router.refresh();
  }

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider.value(value: _authBloc),
        // Cart lives above the router so the nav badge, the Buy Now sheet and
        // the cart page all read the same instance.
        BlocProvider.value(value: getIt<CartBloc>()),
      ],
      child: ListenableBuilder(
        listenable: getIt<LocaleController>(),
        builder: (context, _) {
          final chosen = getIt<LocaleController>().locale;
          // Falls back to Arabic rather than English when the system locale is
          // unsupported — see WaveLocalizations.fallback for why. Used for the
          // THEME only; `locale:` below stays null so the framework can still
          // negotiate among supportedLocales.
          final locale = chosen ?? WaveLocalizations.fallback;

          return MaterialApp.router(
            // onGenerateTitle rather than `title`, so the OS task-switcher
            // label follows the locale like everything else.
            onGenerateTitle: (context) => AppLocalizations.of(context).appName,
            debugShowCheckedModeBanner: false,
            routerConfig: _appRouter.router,
            theme: AppTheme.light(locale),
            darkTheme: AppTheme.dark(locale),
            // Null lets the framework choose among supportedLocales; a value
            // overrides it with the user's explicit pick.
            locale: chosen,
            supportedLocales: WaveLocalizations.supported,
            // Shared with test/helpers/pump_app.dart, so a widget test cannot
            // resolve localizations differently from the app.
            //
            // The list that used to be inlined here named only the three Global
            // delegates, none of which supports ckb. The framework logged
            // "locale ckb is not supported by all of its localization
            // delegates" and carried on: WAVE's own strings rendered in
            // Kurdish while every Material-owned string — Cancel, the date
            // picker, the selection menu — fell back to ENGLISH, for a third of
            // the market. See WaveLocalizations.
            localizationsDelegates: WaveLocalizations.delegates,
            builder: (context, child) {
              // Dynamic type is respected (§3.5), but an unbounded scale factor
              // breaks the price row in the checkout sheet. 1.4 is generous and
              // still lays out correctly.
              final scale = MediaQuery.textScalerOf(context).clamp(
                minScaleFactor: 0.8,
                maxScaleFactor: 1.4,
              );
              return MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaler: scale),
                // گوێگرەکە لێرەدا زیاد کرا
                child: CartMessageListener(
                  // One shimmer clock for the whole app. Mounted here rather
                  // than above MaterialApp because it reads Theme (for
                  // motion.shimmerLoop) and MediaQuery (for disableAnimations),
                  // neither of which exists above the app. Without it every
                  // skeleton renders as a static grey block.
                  child: WaveShimmerScope(child: child!),
                ),
              );
            },
          );
        },
      ),
    );
  }
}

/// Bridges a BLoC stream to GoRouter's Listenable-based refresh.
class _AuthRefreshNotifier extends ChangeNotifier {
  _AuthRefreshNotifier(Stream<AuthState> stream) {
    _subscription = stream.listen((_) => notifyListeners());
  }

  /// Typed, not dynamic.
  ///
  /// It was `late final dynamic`, which made `_subscription.cancel()` an
  /// unchecked dynamic call — the analyzer flagged it (avoid_dynamic_calls at
  /// app.dart:157) and, more to the point, a rename or signature change on
  /// StreamSubscription would have failed at runtime during dispose rather than
  /// at compile time.
  late final StreamSubscription<AuthState> _subscription;

  @override
  void dispose() {
    unawaited(_subscription.cancel());
    super.dispose();
  }
}
