// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2q2Nk1_HmDUrwGX4fXL2jFr931SjgkAs',
    appId: '1:802491262696:web:48ea1bfd114098e7390b5d',
    messagingSenderId: '802491262696',
    projectId: 'wave-dev-bb9da',
    authDomain: 'wave-dev-bb9da.firebaseapp.com',
    storageBucket: 'wave-dev-bb9da.firebasestorage.app',
    measurementId: 'G-WBQWDZRQSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpRJPqLVYKW1ooeNTY7bnBvN-NBV6jMs',
    appId: '1:802491262696:android:e88ec61a912a0a39390b5d',
    messagingSenderId: '802491262696',
    projectId: 'wave-dev-bb9da',
    storageBucket: 'wave-dev-bb9da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx76pN9tc3-rTRprIrTjLbDDjF_Z3dI-I',
    appId: '1:802491262696:ios:3402de6e8af70847390b5d',
    messagingSenderId: '802491262696',
    projectId: 'wave-dev-bb9da',
    storageBucket: 'wave-dev-bb9da.firebasestorage.app',
    iosBundleId: 'com.example.wave',
  );
}
