#!/usr/bin/env python3
"""Generates every derived brand asset from one source image.

    python3 tool/generate_brand_assets.py

The source lives at `assets/brand/source/logo_source.png` and is the only
brand file a designer should ever edit. Everything in `assets/brand/` is
derived and is regenerated by this script.

Checking in derived images without the thing that produced them is how brand
assets rot: six months later nobody knows which PNG was the master, whether the
adaptive icon was cropped correctly, or how to produce a new size. This script
is the answer to all three.

Each target has different, non-obvious constraints, and getting them wrong fails
in ways that only show on a device:

- **iOS app icons must not have an alpha channel.** App Store Connect rejects
  the build; it does not warn.
- **Android adaptive icons are masked to an arbitrary shape** chosen by the
  launcher — circle, squircle, teardrop. Anything outside the inner 66% of the
  canvas may be cut off, and the mark here is wide, so it needs deliberate
  scaling rather than a naive fit.
- **The Android 12+ splash icon is masked to a circle** covering roughly two
  thirds of the canvas. A full-bleed image loses its edges.

The source mark is wide (roughly 1.7:1), which matters more than usual: squaring
a wide mark leaves large vertical margins, and scaling it to fill a square makes
it illegible at 48dp. Every target below scales to a fraction of WIDTH and
accepts the vertical margin.
"""
import os
import sys

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    sys.exit("Pillow is required: pip install Pillow")

SOURCE = "assets/brand/source/logo_source.png"
OUT_DIR = "assets/brand"

# The brand background. Matches `WaveColors.backgroundDark` so the splash does
# not flash a different black before the first frame paints.
BACKGROUND = (5, 6, 10)

# Fraction of canvas WIDTH the mark occupies, per target.
SCALE = {
    # Comfortable margin; the mark still reads at 48dp.
    "icon": 0.78,
    # Adaptive foreground: inside the 66% safe zone with room to spare, because
    # launcher masks vary and a teardrop crops more aggressively than a circle.
    "icon_foreground": 0.60,
    # Splash on iOS and Android 11 and below — centred, no mask.
    "splash": 0.70,
    # Android 12+: masked to a circle over about two thirds of the canvas.
    "splash_android12": 0.52,
    # In-app logo. Trimmed rather than padded; the widget decides the layout.
    "logo": 1.0,
}


def trimmed(image: Image.Image) -> Image.Image:
    """The artwork with its black letterboxing removed and alpha applied.

    The source is RGB on black, so 'transparent' has to be derived from
    luminance rather than read from an alpha channel. A hard threshold would
    leave a halo around the glow, so luminance becomes the alpha value directly
    — which preserves the soft falloff the mark depends on.
    """
    rgba = image.convert("RGBA")
    luminance = image.convert("L")

    rgba.putalpha(luminance)

    box = luminance.point(lambda p: 255 if p > 12 else 0).getbbox()
    if box is None:
        sys.exit("Source image appears to be blank")

    return rgba.crop(box)


def compose(mark: Image.Image, size: int, scale: float, *, opaque: bool) -> Image.Image:
    """Centres `mark` on a square canvas, scaled to `scale` of the width."""
    target_width = max(1, int(size * scale))
    ratio = target_width / mark.width
    resized = mark.resize(
        (target_width, max(1, int(mark.height * ratio))),
        Image.LANCZOS,
    )

    if opaque:
        canvas = Image.new("RGB", (size, size), BACKGROUND)
        canvas.paste(
            resized,
            ((size - resized.width) // 2, (size - resized.height) // 2),
            resized,
        )
        return canvas

    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.paste(
        resized,
        ((size - resized.width) // 2, (size - resized.height) // 2),
    )
    return canvas


def main() -> int:
    if not os.path.exists(SOURCE):
        sys.exit(f"Missing source image: {SOURCE}")

    mark = trimmed(Image.open(SOURCE))
    print(f"source mark: {mark.width}x{mark.height}")

    targets = [
        # name, size, opaque
        # Opaque: App Store Connect rejects an icon with an alpha channel, and
        # does so at upload rather than at review, after you have waited.
        ("icon", 1024, True),
        ("icon_foreground", 1024, False),
        ("splash", 1024, False),
        ("splash_android12", 1152, False),
    ]

    for name, size, opaque in targets:
        out = compose(mark, size, SCALE[name], opaque=opaque)
        path = os.path.join(OUT_DIR, f"{name}.png")
        out.save(path, "PNG", optimize=True)
        print(f"  {name + '.png':24} {out.size} {out.mode}")

    # The in-app logo keeps its own aspect ratio. Padding it into a square would
    # force every widget using it to undo the padding.
    logo_width = 1024
    logo = mark.resize(
        (logo_width, max(1, int(mark.height * logo_width / mark.width))),
        Image.LANCZOS,
    )
    logo.save(os.path.join(OUT_DIR, "logo.png"), "PNG", optimize=True)
    print(f"  {'logo.png':24} {logo.size} {logo.mode}")

    # Guard the constraint that fails silently at upload time.
    icon = Image.open(os.path.join(OUT_DIR, "icon.png"))
    if icon.mode != "RGB":
        sys.exit("icon.png must have no alpha channel — iOS rejects it")

    print("\nNext:")
    print("  dart run flutter_launcher_icons")
    print("  dart run flutter_native_splash:create")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
